#!/usr/bin/env python3
"""Developer surfaces: CLI explorer and contributor hub."""
from __future__ import annotations
from pathlib import Path
import hashlib, html, json, os, re
ROOT=Path(__file__).resolve().parents[1]; ASSETS=ROOT/'assets'; API=ROOT/'api/v1'
SITE=(os.getenv('RAZ_SITE_URL') or 'https://raz-language.github.io').strip().rstrip('/')
def e(v): return html.escape(str(v),quote=True)
def shell(path):
 t=path.read_text(encoding='utf-8'); m=re.search(r'<header class="(?:marketing-hero|section-hero|product-masthead|reference-header)[^"]*".*?</header>',t,re.S); f=t.find('<footer class="site-footer">')
 if not m or f<0: raise SystemExit(f'bad shell {path}')
 return t[:m.start()],t[f:]
def head(t,title,desc,url,typ='TechArticle'):
 repl=[(r'<title>.*?</title>',f'<title>{e(title)}</title>'),(r'<meta name="description" content="[^"]*">',f'<meta name="description" content="{e(desc)}">'),(r'<meta property="og:title" content="[^"]*">',f'<meta property="og:title" content="{e(title)}">'),(r'<meta property="og:description" content="[^"]*">',f'<meta property="og:description" content="{e(desc)}">'),(r'<meta name="twitter:title" content="[^"]*">',f'<meta name="twitter:title" content="{e(title)}">'),(r'<meta name="twitter:description" content="[^"]*">',f'<meta name="twitter:description" content="{e(desc)}">'),(r'<link rel="canonical" href="[^"]*">',f'<link rel="canonical" href="{e(url)}">'),(r'<meta property="og:url" content="[^"]*">',f'<meta property="og:url" content="{e(url)}">')]
 for a,b in repl:t=re.sub(a,b,t,count=1,flags=re.S)
 schema={'@context':'https://schema.org','@type':typ,'headline':title,'description':desc,'url':url}
 return re.sub(r'<script type="application/ld\+json" data-v24-schema="page">.*?</script>',lambda _m:'<script type="application/ld+json" data-v24-schema="page">'+json.dumps(schema,separators=(',',':'))+'</script>',t,count=1,flags=re.S)
COMMANDS=[
 ('general','doctor','raz doctor','Inspect host/toolchain and project health.'),('general','backends','raz backends','List available code-generation backends.'),('general','targets','raz targets','List supported target triples.'),('general','diagnostics','raz diagnostics','Print the compiler diagnostic catalog.'),
 ('build','build','raz build [options] [input] [output]','Build a project or source input; use --release for the release profile.'),('build','run','raz run <input>','Build and run a native project, forwarding program args after --.'),('build','check','raz check <input>','Type-check and validate without producing the normal executable.'),('build','test','raz test [--filter=<text>] <input>','Run discovered test_ functions, optionally filtered.'),('build','lint','raz lint <input>','Run compiler lint/warning analysis.'),
 ('project','new','raz new <name>','Create a new Raz project.'),('project','init','raz init [path]','Initialize a project in a directory.'),('project','clean','raz clean','Remove project-local generated state under target/.'),('project','fmt','raz fmt [--check] [file-or-directory]','Format Raz source or verify formatting.'),('project','doc','raz doc <file.rz> [output.md]','Generate source documentation.'),
 ('package','search','raz search <query>','Search the official static package index.'),('package','info','raz info <package>','Inspect package metadata.'),('package','add','raz add <package>[@<constraint>]','Add a registry, path, or explicitly named dependency.'),('package','remove','raz remove <alias>','Remove a dependency.'),('package','outdated','raz outdated','Report newer versions for tracked registry dependencies.'),('package','install','raz install <package>[@<constraint>]','Install executable package targets into the managed user bin directory.'),('package','uninstall','raz uninstall <package>','Remove a managed package tool.'),('package','vendor','raz vendor [--check]','Materialize or verify the vendored dependency tree.'),('package','update','raz update','Resolve/update dependencies and the lockfile.'),('package','lock','raz lock','Resolve and write the lockfile.'),('package','metadata','raz metadata','Emit project/package metadata.'),('package','graph','raz graph','Emit the dependency graph.'),('package','tree','raz tree','Display dependency relationships.'),('package','fetch','raz fetch','Fetch locked dependencies.'),('package','pack','raz pack [output.dpk]','Create a deterministic package archive.'),('package','publish','raz publish','Prepare/publish a package submission.'),('package','keygen','raz keygen [prefix]','Generate an Ed25519 package-signing key pair.'),
 ('interop','bindgen','raz bindgen <header.h> [--target-abi=windows|unix] [output.rz]','Translate supported C declarations into Raz.'),('interop','c-header','raz c-header <source.rz|directory> [output.h]','Generate a C header for explicit C-ABI Raz exports.'),
 ('backend','forge','raz forge <input> <output.fir>','Request Forge IR or Forge-native backend output.'),('backend','llvm','raz llvm --emit=<kind> <input> <output>','Use LLVM-specific emission and cross-target options.')]
CATS=[('general','Toolchain'),('build','Build & execute'),('project','Projects'),('package','Packages'),('interop','C interoperability'),('backend','Backends')]
def make_cli():
 pre,foot=shell(ROOT/'tools/index.html'); title='Raz CLI Reference — Commands and workflows'; desc='Searchable Raz command reference for builds, projects, packages, backends, diagnostics and C interoperability.'; url=SITE+'/cli/'; pre=head(pre,title,desc,url)
 cards=[]
 for cat,label in CATS:
  rows=[]
  for c,n,u,d in COMMANDS:
   if c!=cat:continue
   rows.append(f'<article class="cli-command" id="{e(n)}" data-cli-command data-name="{e(n)}" data-category="{e(cat)}"><div class="cli-command-head"><div><a class="cli-anchor" href="#{e(n)}">raz {e(n)}</a><span>{e(label)}</span></div><button class="copy-button" type="button" data-copy="{e(u)}">Copy</button></div><code>{e(u)}</code><p>{e(d)}</p><div class="cli-command-links"><a href="https://github.com/raz-language/raz/blob/main/docs/CLI.md">Canonical CLI docs ↗</a><a href="https://github.com/raz-language/raz">Source ↗</a></div></article>')
  cards.append(f'<section class="cli-group" data-cli-group><div class="cli-group-title"><h2>{e(label)}</h2><span>{len(rows)} commands</span></div>'+''.join(rows)+'</section>')
 body=f'''<header class="product-masthead cli-masthead"><div class="shell"><p class="kicker">CLI REFERENCE</p><h1><code>raz</code> commands</h1><p>Find the command you need without scanning a monolithic reference document.</p><div class="cli-find"><label for="cli-search">Search commands</label><input id="cli-search" type="search" placeholder="build, install, diagnostics…" autocomplete="off" data-cli-search><span data-cli-count>{len(COMMANDS)} commands</span></div></div></header><main id="main" class="after-hero"><section class="section section-white"><div class="shell cli-layout"><aside class="cli-sidebar"><p>COMMAND GROUPS</p>{''.join(f'<a href="#group-{c}">{e(l)}</a>' for c,l in CATS)}<hr><a href="https://github.com/raz-language/raz/blob/main/docs/CLI.md">Canonical CLI.md ↗</a></aside><div class="cli-content"><div class="source-banner"><b>Source of truth</b><span>This explorer is a navigation surface. The canonical command contract remains <code>raz/docs/CLI.md</code> and command-specific <code>raz &lt;command&gt; --help</code>.</span></div>{''.join(x.replace('class="cli-group"',f'class="cli-group" id="group-{CATS[i][0]}"',1) for i,x in enumerate(cards))}<p class="cli-empty" data-cli-empty hidden>No commands match that search.</p></div></div></section></main><script data-cli-controller>(()=>{{const input=document.querySelector('[data-cli-search]'),rows=[...document.querySelectorAll('[data-cli-command]')],groups=[...document.querySelectorAll('[data-cli-group]')],count=document.querySelector('[data-cli-count]'),empty=document.querySelector('[data-cli-empty]');if(!input)return;const run=()=>{{const q=input.value.trim().toLowerCase();let shown=0;rows.forEach(r=>{{const ok=!q||r.textContent.toLowerCase().includes(q);r.hidden=!ok;if(ok)shown++}});groups.forEach(g=>g.hidden=![...g.querySelectorAll('[data-cli-command]')].some(r=>!r.hidden));count.textContent=shown+' command'+(shown===1?'':'s');empty.hidden=shown!==0}};input.addEventListener('input',run);}})();</script>'''
 p=ROOT/'cli/index.html';p.parent.mkdir(parents=True,exist_ok=True);p.write_text(pre+body+foot,encoding='utf-8')
 payload={'schema':'raz-cli-site-v1','source':'https://github.com/raz-language/raz/blob/main/docs/CLI.md','commands':[{'category':c,'name':n,'usage':u,'description':d,'url':f'/cli/#{n}'} for c,n,u,d in COMMANDS]};(API/'cli.json').write_text(json.dumps(payload,indent=2)+'\n',encoding='utf-8')
def make_contribute():
 pre,foot=shell(ROOT/'ecosystem/index.html'); title='Contribute to Raz — Repository ownership and required checks';desc='Contribution guide for the Raz compiler, Forge, ObLink, packages, installer and editor tooling.';url=SITE+'/contribute/';pre=head(pre,title,desc,url)
 body='''<header class="section-hero"><div class="shell narrow"><p class="kicker">CONTRIBUTE</p><h1>Change the right layer. Prove it still works.</h1><p class="page-lead">Raz is split across independently owned components, but compiler correctness, determinism and synchronized integration are shared project contracts.</p><div class="button-row"><a class="button button-primary" href="https://github.com/raz-language/raz/blob/main/CONTRIBUTING.md">Canonical contributing guide ↗</a><a class="button button-secondary" href="../ecosystem/index.html">Ecosystem map</a></div></div></header><main id="main" class="after-hero"><section class="section section-white"><div class="shell"><div class="section-top compact"><div><p class="kicker">OWNERSHIP</p><h2>Start in the canonical repository.</h2></div><p>Do not work around a language/compiler problem in another layer. Make the change where the behavior is owned, then synchronize integration copies when required.</p></div><div class="ownership-grid"><article><b>raz</b><h3>Language + compiler</h3><p>Language semantics, HIR/MIR, CLI/project driver, runtime boundaries and LSP integration.</p></article><article><b>forge</b><h3>Native backend</h3><p>Forge IR, optimization, machine lowering and standalone backend tools.</p></article><article><b>oblink</b><h3>Native linker</h3><p>Object/link behavior and linker-specific platform support.</p></article><article><b>packages</b><h3>Registry packages</h3><p>Official package sources, versions and registry index state.</p></article><article><b>installer</b><h3>Distribution</h3><p>MSI, portable archives, channel manifests and release packaging.</p></article><article><b>raz-vscode</b><h3>Editor UX</h3><p>VS Code integration built on compiler/LSP capabilities.</p></article></div></div></section><section class="section section-soft"><div class="shell two-col"><div><p class="kicker">BASELINE CHECK</p><h2>Normal compiler work.</h2><p class="section-copy">The Raz contribution guide requires a debug configure/build/test cycle, plus focused checks that match the subsystem being changed.</p></div><div class="code-card"><div class="code-bar"><span>compiler repository</span></div><pre><code>cmake --preset debug
cmake --build --preset debug
ctest --preset debug</code></pre></div></div></section><section class="section section-white"><div class="shell"><div class="section-top compact"><div><p class="kicker">EMBEDDED COMPONENTS</p><h2>Forge and ObLink are mirrors, not forks.</h2></div><p>Make maintained component changes in the standalone repository first, then synchronize the embedded copy carried by Raz and verify byte identity.</p></div><div class="code-card contributor-sync"><div class="code-bar"><span>synchronize integration copies</span></div><pre><code>python tools/sync-embedded-components.py
python tools/check-embedded-components.py</code></pre></div><div class="contribution-rules"><article><span>01</span><h3>Language behavior belongs in Raz</h3><p>Do not move semantics into native shims because the language implementation is harder.</p></article><article><span>02</span><h3>Preserve determinism</h3><p>Source discovery, dependency ordering, generated identifiers and compiler output must remain reproducible.</p></article><article><span>03</span><h3>Qualify the whole affected path</h3><p>A feature is not complete merely because it parses; test semantic, MIR, backend and execution behavior where applicable.</p></article><article><span>04</span><h3>Keep generated state out</h3><p>Build products, caches and project targets are generated state rather than source.</p></article></div></div></section></main>'''
 p=ROOT/'contribute/index.html';p.parent.mkdir(parents=True,exist_ok=True);p.write_text(pre+body+foot,encoding='utf-8')
def update_footer():
 for p in ROOT.rglob('*.html'):
  if '_site' in p.parts:continue
  t=p.read_text(encoding='utf-8'); rel=p.relative_to(ROOT); prefix='../'*max(0,len(rel.parts)-1)
  t=re.sub(r'<a data-project-cli-link[^>]*>CLI</a><a data-project-contribute-link[^>]*>Contribute</a>','',t)
  m=re.search(r'<a data-project-performance-link[^>]*>Performance</a>',t)
  if m:
   ins=f'<a data-project-cli-link href="{prefix}cli/index.html">CLI</a><a data-project-contribute-link href="{prefix}contribute/index.html">Contribute</a>';t=t[:m.end()]+ins+t[m.end():]
  p.write_text(t,encoding='utf-8')
def search():
 p=ASSETS/'search-core.json';items=json.loads(p.read_text()); items=[i for i in items if i.get('kind') not in {'cli-command','contribute'} and i.get('url') not in {'cli/index.html','contribute/index.html'}]
 items += [{'title':'Raz CLI Reference','description':'Searchable command reference for the Raz project driver.','url':'cli/index.html','keywords':'cli commands raz build run install packages diagnostics','kind':'cli','name':'Raz CLI','namespace':'raz','qualified_name':'raz'}, {'title':'Contribute to Raz','description':'Repository ownership, required checks and component synchronization.','url':'contribute/index.html','keywords':'contribute contributing compiler forge oblink tests repository','kind':'contribute','name':'Contribute to Raz','namespace':'','qualified_name':'Contribute to Raz'}]
 for c,n,u,d in COMMANDS:items.append({'title':u,'description':d,'url':f'cli/index.html#{n}','keywords':f'cli command raz {n} {c} {u}','kind':'cli-command','name':n,'namespace':'raz','qualified_name':f'raz {n}'})
 p.write_text(json.dumps(items,separators=(',',':'))+'\n')
 js=ASSETS/'site.js';t=js.read_text();cd=hashlib.sha256(p.read_bytes()).hexdigest()[:12];ad=hashlib.sha256((ASSETS/'search-api.json').read_bytes()).hexdigest()[:12];t=re.sub(r"const coreVersion='[0-9a-f]{12}',apiVersion='[0-9a-f]{12}';",f"const coreVersion='{cd}',apiVersion='{ad}';",t,count=1);js.write_text(t)
def styles():
 p=ASSETS/'styles.css';t=p.read_text();marker='/* v30 CLI + contribution surfaces */';t=t.split(marker,1)[0].rstrip()+'\n' if marker in t else t
 t+='''\n/* v30 CLI + contribution surfaces */
.cli-masthead .shell{max-width:1000px}.cli-find{display:grid;grid-template-columns:auto minmax(240px,1fr) auto;gap:12px;align-items:center;margin-top:22px}.cli-find label{font-weight:800;font-size:.78rem}.cli-find input{min-height:44px;border:1px solid var(--line);border-radius:6px;padding:0 13px;font:inherit}.cli-find span{font-size:.76rem;color:var(--muted)}.cli-layout{display:grid;grid-template-columns:190px minmax(0,1fr);gap:34px}.cli-sidebar{position:sticky;top:90px;align-self:start;display:grid;gap:8px}.cli-sidebar p{font-size:.65rem;font-weight:900;letter-spacing:.14em}.cli-sidebar a{font-size:.78rem}.cli-sidebar hr{width:100%;border:0;border-top:1px solid var(--line)}.source-banner{display:grid;grid-template-columns:auto 1fr;gap:12px;padding:15px;border:1px solid var(--line);background:var(--soft);margin-bottom:30px}.source-banner span{font-size:.8rem;color:var(--muted)}.cli-group{scroll-margin-top:90px;margin:0 0 34px}.cli-group-title{display:flex;justify-content:space-between;align-items:baseline;border-bottom:1px solid var(--line);padding-bottom:10px;margin-bottom:12px}.cli-group-title h2{margin:0}.cli-group-title span{color:var(--muted);font-size:.72rem}.cli-command{scroll-margin-top:90px;border-bottom:1px solid var(--line);padding:18px 0}.cli-command-head{display:flex;justify-content:space-between;gap:16px;align-items:start}.cli-command-head>div{display:grid;gap:3px}.cli-anchor{font-family:var(--mono);font-weight:850;font-size:1rem}.cli-command-head span{font-size:.68rem;color:var(--muted);text-transform:uppercase;letter-spacing:.08em}.cli-command>code{display:block;margin:12px 0;padding:10px 12px;background:#f5f5f3;white-space:pre-wrap;overflow-wrap:anywhere}.cli-command p{margin:0;color:var(--muted);font-size:.86rem}.cli-command-links{display:flex;gap:14px;margin-top:10px;font-size:.72rem}.cli-empty{text-align:center;padding:50px;color:var(--muted)}.ownership-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:26px}.ownership-grid article{border:1px solid var(--line);padding:22px}.ownership-grid b{font-family:var(--mono)}.ownership-grid h3{margin:8px 0}.ownership-grid p{margin:0;color:var(--muted);font-size:.82rem}.contributor-sync{max-width:760px}.contribution-rules{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:25px}.contribution-rules article{border:1px solid var(--line);padding:20px}.contribution-rules span{font-weight:900;font-size:.68rem}.contribution-rules p{color:var(--muted);font-size:.8rem}
@media(max-width:850px){.cli-layout{grid-template-columns:1fr}.cli-sidebar{position:static;grid-template-columns:repeat(3,1fr);border-bottom:1px solid var(--line);padding-bottom:18px}.cli-sidebar p,.cli-sidebar hr{display:none}.ownership-grid{grid-template-columns:1fr 1fr}.contribution-rules{grid-template-columns:1fr 1fr}}
@media(max-width:600px){.cli-find{grid-template-columns:1fr}.cli-find span{justify-self:start}.cli-sidebar{grid-template-columns:1fr 1fr}.ownership-grid,.contribution-rules{grid-template-columns:1fr}.cli-command-head{align-items:center}.cli-command-links{flex-direction:column;gap:5px}}
''';p.write_text(t)
def api_index():
 p=API/'index.json';d=json.loads(p.read_text());d.setdefault('resources',{})['cli']='./cli.json';p.write_text(json.dumps(d,indent=2,sort_keys=True)+'\n')
def sitemap():
 p=ROOT/'sitemap.xml'; urls=[]
 for page in sorted(ROOT.rglob('*.html')):
  rel=page.relative_to(ROOT)
  if '_site' in rel.parts or rel.as_posix()=='404.html':continue
  t=page.read_text(errors='ignore')
  if re.search(r'<meta name="robots" content="[^"]*noindex',t,re.I):continue
  route='/' if rel.as_posix()=='index.html' else '/'+rel.as_posix().removesuffix('index.html');urls.append(SITE+route)
 p.write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'  <url><loc>{e(u)}</loc></url>\n' for u in urls)+'</urlset>\n')
def main():
 make_cli();make_contribute();update_footer();search();styles();api_index();sitemap();print(f'v30: CLI explorer ({len(COMMANDS)} commands) + contributor hub')
if __name__=='__main__':main()
